# fly.toml app configuration file generated for offer-calculator-api on 2026-02-03T21:15:06+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'offer-calculator-api'
primary_region = 'ams'

[build]
  dockerfile = "packages/apps/api/Dockerfile"
  build-target = "runner"

[deploy]
  release_command = "pnpm --filter @projektownia-calculator/api run migrate:deploy"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
